config/routes.rb
Polls::Application.routes.draw do

  resources :answers

  root :to => "Polls#index"


  resources :polls do
    resources :questions
  end
  get "/:slug" => "Polls#show_by_slug "


  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :body, :question_id
  belongs_to      :question
end

app/models/poll.rb
class Poll < ActiveRecord::Base  
  validates :name, :presence => true
  before_create :slug_save

  attr_accessible :name, :slug, :name

  has_many :questions, :dependent => :destroy

  def slug_save
    string = ""
    6.times do
      string << rand(1..9).to_s
    end
    self.slug = string
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :body
  belongs_to      :poll
  has_many        :answers, :dependent => :destroy
  accepts_nested_attributes_for :answers

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :assign_question

  def index
    @answers = @question.answers
  end

  def show
    @answer = Answer.find(params[:id])
  end

  def new
    @answer = Question.find(params[:question_id]).answers.create
  end

  def edit
    @answer = @question.answers.find(params[:id])
  end

  def create
    @poll = Poll.find(params[:poll_id])
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(params[:answer])

     respond_to do |format|
       if @answer.save
         format.html { redirect_to poll_questions_path(@poll)}
       else
         format.html { render action: "new" }
       end
     end
   end

  def update
    @answer = @question.answers.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to answers_path(@question)  }
      else
        format.html { render action: "edit" }
      end
     end
  end

  def destroy
    @answer = @question.answers.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_path(@question) }
     end
   end

  private
    def assign_question
      @question = Question.find(params[:question_id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  def index
    @polls = Poll.all
  end

  def show_by_slug
     @poll = Poll.find_by_slug(params[:slug])
  end

  def show
    @poll = Poll.find(params[:id])
  end

  def new
    @poll = Poll.new
    # :notice => "The encrypted url(slug) for your poll is #{@poll.slug}"
    3.times {@poll.questions.build}
  end

  def edit
    @poll = Poll.find(params[:id])
  end

  def create
    @poll = Poll.new(params[:poll])

    respond_to do |format|
      if @poll.save

        # link = "<a href=/localhost:3000/#{@poll.slug}>link</a>".html_safe

        format.html { redirect_to @poll, notice: "Poll was successfully created. Slug url => localhost:3000/#{@poll.slug}" }
      else
        format.html { render action: "new" }}
      end
    end
  end


  def update
    @poll = Poll.find(params[:id])

    respond_to do |format|
      if @poll.update_attributes(params[:poll])
        format.html { redirect_to root_path, notice: 'Poll was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @poll = Poll.find(params[:id])
    @poll.destroy

    respond_to do |format|
      format.html { redirect_to polls_url }
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

   before_filter :assign_poll

   def index
      @questions = @poll.questions
   end

   def show
      @question = Question.find(params[:id])
   end


    def new
      @question = Question.new
      3.times {@question.answers.build}
      # :notice => "The encrypted url(slug) for your poll is #{@question.slug}"
      #flash[:notice] => "The encrypted url(slug) for your poll is #{@answer.slug}",
    end

    def edit
      @question = @poll.questions.find(params[:id])
    end


    def create
      @question = @poll.questions.new(params[:question])

      respond_to do |format|
        if @question.save
          format.html {  redirect_to poll_questions_path(@poll) }
        else
          format.html { render action: "new" 
        end
      end
    end

    def update
      @question = @poll.questions.find(params[:id])

      respond_to do |format|
        if @question.update_attributes(params[:question])
          format.html { redirect_to poll_questions_path(@poll)  }
        else
          format.html { render action: "edit" }
        end
      end
    end

    def destroy
      @question = @poll.questions.find(params[:id])
      @question.destroy

      respond_to do |format|
        format.html { redirect_to poll_questions_path(@poll) }
      end
    end

    private

    def assign_poll
      @poll = Poll.find(params[:poll_id])
    end
  end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.erb
<%= form_for @answer, :url => answers_path + "?poll_id=#{params[:poll_id]}&question_id=#{params[:question_id]}", :method => :post, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="control-group">
    <%= f.label @question.body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :body, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit 'Save Answer', :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                poll_questions_path(@question.poll), :class => 'btn' %>
  </div>
<% end %>

app/views/answers/index.html.erb
<%= debug params %>
<h2><%= @question.body %></h2>

<% @answers.each do |a| %>
  <% unless a.body.nil? %>
    <%= a.body %><br>
  <% end %>
<% end %>

app/views/answers/new.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.body', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>  
<%= render :partial => 'form' %>

app/views/answers/show.html.erb
<%- model_class = Answer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @answer.body %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              answers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_answer_path(@question), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              answer_path(@question),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Polls" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>



 

       

    <div class="container">
	    <div class = "index_link">       
	    <a class="brand" href="http://localhost:3000/">Pollster</a> 
	    </div>
	    <div class="tagline"><p> Create, Edit, Respond to Polls. In a very dangerous way.</p> </div>
        <div class="row">
          <div class="span12">
             <%= yield %>
          </div> 
        </div>
         

            <% flash.each do |name, message|%>
              <div id="flash_<%= name%>">
                <%= message %>
              </div>
            <% end %>

      <footer>
        <p>&copy; L&F limited</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/polls/_form.html.erb
<%= form_for @poll, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                polls_path, :class => 'btn' %>
  </div>
<% end %>

app/views/polls/edit.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/polls/index.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:Poll_link) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= link_to poll.name, poll_path(poll) %></td>
        <td>
	       	<%= link_to "See the poll questions",
				                          poll_questions_path(poll), :class => 'btn'  %>
          <%= link_to "Edit this poll", edit_poll_path(poll), :class => 'btn btn-mini' %>
          <%= link_to "Destroy this poll",
                      poll_path(poll),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Create your own poll",
            new_poll_path,
            :class => 'btn btn-primary' %>

app/views/polls/new.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/polls/show.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @poll.name %></dd>
</dl>



<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              polls_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_poll_path(@poll), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              poll_path(@poll),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

  <%= link_to "Create a new question", new_poll_question_path(@poll), :class => 'btn'  %>
</div>

app/views/polls/show_by_slug.html.erb
<%- model_class = Poll -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @poll.name %></dd>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:slug) %>:</strong></dt>
  <dd><%= @poll.slug %></dd>
</dl>



<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              polls_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_poll_path(@poll), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              poll_path(@poll),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/questions/_form.html.erb
<%= form_for [@poll,@question], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group"> 
	  <h2><%= @poll.name%></h2>
    <%= f.label :question, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :body, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                poll_questions_path(@poll), :class => 'btn' %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/index.html.erb
<%- model_class = Question -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize %> for:</h1>          	 
      <h2><%= @poll.name %></h2>
	</div>       


<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:question) %></th>
      <th><%=t 'Things to do'%></th>
      <th><%= model_class.human_attribute_name(:answers) %></th>

    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to question.body, poll_question_path(@poll, question)%> </td>

        <td>
           <%= link_to "Edit the question",
                        edit_poll_question_path(@poll,question), :class => 'btn btn-mini' %>

           <%= link_to "Answer the question",
                                      new_answer_path(:question_id => question, :poll_id => @poll.id), :class => 'btn btn-mini' %>

          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      poll_question_path(@poll,question),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %> 

        </td> 
        <td>&nbsp;</td>

      </tr>
      <% question.answers.reject{|a| a.body.nil? }.each do |a| %>
      <tr>
        <td colspan="1">&nbsp;</td>
        <td colspan="1">&nbsp;</td>
        <td colspan="1"><%= a.body %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to "Create a new Question",new_poll_question_path, :class => 'question_button' %>

app/views/questions/new.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div> 
<h2><%= @question.poll_id %> </h2>
<%= render :partial => 'form' %>

app/views/questions/show.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @question.body %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              poll_questions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_poll_question_path(@poll, @question), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              poll_question_path(@poll, @question),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>